---
title: "Storage-harvest"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load data

Next, need to load z and calculate spread as of Oct 1

```{r}
library(tidyverse)
library(profvis)
library(lubridate)
tick_ <- list("70", "71", "72", "73", "74", "75", "76", "77", "78", "79", 
              "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", 
              "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", 
              "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", 
              "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", 
              "20")
start_<- list("1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1977", "1979", 
              "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", 
              "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", 
              "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", 
              "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", 
              "2020")

j = 3

#data <- read.csv(file=paste0("data/zch", tick_[[j]],".csv"), header=TRUE, sep=",")
# change to real time  download to explore longer history
data <- read.csv(paste0('http://ondemand.websol.barchart.com/getHistory.csv?apikey=c3122f072488a29c5279680b9a2cf88e&symbol=zch', tick_[[j]], '&type=daily&startDate=', start_[[j-1]], '0901'))
data1 <- read.csv(paste0('http://ondemand.websol.barchart.com/getHistory.csv?apikey=c3122f072488a29c5279680b9a2cf88e&symbol=zcz', tick_[[j-1]], '&type=daily&startDate=', start_[[j-1]], '0901'))
data <- left_join(data, data1, by = "tradingDay", suffix = c(".h", ".z"))

# Take only mondays, 
# calculate days since Oct 1, 
# then select days since and close price

data <- data %>% 
  select(symbol.h, symbol.z, tradingDay, close.h, close.z) %>%
  mutate(zh_spread = close.z[10] - close.h[10]) %>%
  mutate(weekday = wday(tradingDay)) %>% 
  filter(weekday == 2) %>%
  mutate(dayssince = as.numeric(as.Date(tradingDay) - as.Date(paste0(start_[[j-1]], '-10-01')))) %>%
  #filter(dayssince > 100) %>%
  select(c(tradingDay, symbol.h, symbol.z, dayssince, close.h, close.z, zh_spread)) %>%
  mutate(close_normalized = close.h/close.h[10])  %>%
  mutate(retwstop = case_when(1-close_normalized < -.05 ~ -.05,
                              1-close_normalized >= -.05 ~ 1-close_normalized))

for(j in 4:length(tick_)){
data_temp <- read.csv(paste0('http://ondemand.websol.barchart.com/getHistory.csv?apikey=c3122f072488a29c5279680b9a2cf88e&symbol=zch', tick_[[j]], '&type=daily&startDate=', start_[[j-1]], '0901'))
data1 <- read.csv(paste0('http://ondemand.websol.barchart.com/getHistory.csv?apikey=c3122f072488a29c5279680b9a2cf88e&symbol=zcz', tick_[[j-1]], '&type=daily&startDate=', start_[[j-1]], '0901'))
data_temp <- left_join(data_temp, data1, by = "tradingDay", suffix = c(".h", ".z"))

# Take only mondays, 
# calculate days since Oct 1, 
# then select days since and close price

data_temp <- data_temp %>% 
  select(symbol.h, symbol.z, tradingDay, close.h, close.z) %>%
  mutate(zh_spread = close.z[10] - close.h[10]) %>%
  mutate(weekday = wday(tradingDay)) %>% 
  filter(weekday == 2) %>%
  mutate(dayssince = as.numeric(as.Date(tradingDay) - as.Date(paste0(start_[[j-1]], '-10-01')))) %>%
  #filter(dayssince > 100) %>%
  select(c(tradingDay, symbol.h, symbol.z, dayssince, close.h, close.z, zh_spread)) %>%
  mutate(close_normalized = close.h/close.h[10]) %>%
  mutate(retwstop = case_when(1-close_normalized < -.05 ~ -.05,
                              1-close_normalized >= -.05 ~ 1-close_normalized))

data <- rbind(data, data_temp)

}
data

```

```{r, fig.width=8, fig.height=5.5}
ggplot(data, aes(x = dayssince, y = close_normalized, color = symbol.h)) + 
  geom_line() + 
  geom_text(data = subset(data, dayssince > 149), aes(label = symbol.h)) +
  theme_bw() +
  theme(legend.position = "none") +
  labs(title = "March Corn Price Deviation Since October 1, 2000-2019", x = "Calendar days since Oct 1")
```


```{r, fig.width=8, fig.height=5.5}

data %>% filter(dayssince >143 & dayssince < 151) %>%
ggplot(aes(x = zh_spread, y = close_normalized, color = symbol.h)) + 
  #geom_point() +
  geom_text(aes(label = symbol.h)) +
  theme_bw() +
  theme(legend.position = "none") +
  labs(title = "March Corn Price Deviation Since October 1, 2000-2019", x = "z-h Spread on Oct 1")
```

```{r, fig.width=8, fig.height=5.5}

data %>% filter(dayssince >143 & dayssince < 151) %>%
ggplot(aes(x = zh_spread, y = retwstop, color = symbol.h)) + 
  #geom_point() +
  geom_text(aes(label = symbol.h)) +
  theme_bw() +
  theme(legend.position = "none") +
  labs(title = "March Corn Short Return w 5% stop Since October 1, 2000-2019", x = "z-h Spread on Oct 1")
```



```{r, fig.width=8, fig.height=5.5}

data %>% filter(dayssince >143 & dayssince < 151) %>%
ggplot(aes(x = retwstop)) + 
  geom_histogram(bins = 15) +
  theme_bw() +
  theme(legend.position = "none") +
  labs(title = "March Corn Short Return w 5% stop Since October 1, 2000-2019", x = "z-h Spread on Oct 1")
```


```{r}
data %>% filter(dayssince >143 & dayssince < 151) %>% summarize(mean = mean(retwstop), median = median(retwstop), min = min(retwstop), max = max(retwstop))


```
